onlyBuiltDependencies:
  - "openseadragon"
allowBuilds:
  '@fortawesome/fontawesome-common-types': set this to true or false
  '@fortawesome/fontawesome-svg-core': set this to true or false
  '@fortawesome/free-regular-svg-icons': set this to true or false
  '@fortawesome/free-solid-svg-icons': set this to true or false
  core-js: set this to true or false
  node-sass: set this to true or false
  openseadragon@https://codeload.github.com/thejohnhoffer/openseadragon/tar.gz/88a3858e8bb38d90831f2ae410e24ec7b8eb8873: true
